version: '3.3'

volumes:
  postgres_data:

services:

  db:
    image: postgres:12.4
    #container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    
  web:
    image: aleksey13ru/foodgram:v.21.06.2021
    #container_name: web_app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./static:/code/static
      - ./media:/code/media
  
  nginx:
    image: nginx:1.19.9-alpine
    #container_name: my_nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/django/static:ro
      - ./media:/var/www/django/media:ro
    depends_on:
      - web
    ports:
      - 80:80    
