# Generated by Django 2.2.20 on 2021-04-20 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='basket',
            field=models.ManyToManyField(blank=True, related_name='baskets', to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='in_favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='избранное'),
        ),
    ]
