# Generated by Django 2.2.20 on 2021-04-21 09:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210420_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], default='dinner', max_length=22, verbose_name='Тег'),
            preserve_default=False,
        ),
    ]
