# Generated by Django 2.2.20 on 2021-04-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='basket',
            field=models.ManyToManyField(blank=True, related_name='baskets', to='recipes.Ingredient', verbose_name='корзина покупок'),
        ),
    ]
