# Generated by Django 2.2.20 on 2021-05-05 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20210423_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='basket',
        ),
        migrations.AddField(
            model_name='recipe',
            name='in_basket',
            field=models.ManyToManyField(blank=True, related_name='basket', to=settings.AUTH_USER_MODEL, verbose_name='корзина покупок'),
        ),
    ]
