# Generated by Django 2.2.20 on 2021-05-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210513_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='dimension',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='title',
        ),
    ]
