# Generated by Django 2.2.20 on 2021-06-30 11:32

from django.db import migrations, models
import recipes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210625_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[recipes.utils.validate_even], verbose_name='Время приготовления'),
        ),
    ]
